-- vim.g.tokyonight_transparent_sidebar = true
-- vim.g.tokyonight_transparent = true
-- vim.opt.background = "dark"
--
-- require("tokyonight").setup({
--   style = "night",
--   light_style = "day",
--   transparent = true,
--   styles = {
--     sidebars = "transparent",
--     floats = "transparent",
--   },
-- })
--
-- vim.cmd("colorscheme tokyonight")
